name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Install dependencies
      run: yarn install

    - name: Deploy
      run: yarn deploy:v2

    - name: Invalidate caches
      env:
        BUNNY_API_KEY: ${{ secrets.BUNNY_API_KEY }}
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/e929f76cdc9368236af764af1b39613c/purge_cache" -H "Authorization: Bearer $CLOUDFLARE_API_KEY" -H "Content-Type: application/json" --data "{ \"purge_everything\": true }"
